services:
  http-svc:
    image: nginx:alpine3.21
    container_name: http-c
    ports:
      - 8080:80
    volumes:
      - ./volumes/config/conf.d:/etc/nginx/conf.d
      - ./volumes/config/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/html:/usr/share/nginx/html




