services:
  fp-svc:
    container_name: fp-c
    build:
      context: ./
      additional_contexts:
        - final_project=./final-project
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf.d:/etc/nginx/conf.d
  hp-svc:
    image: nginx:latest
    container_name: hp-c
    volumes:
      - ./volumes/final-project/config/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/final-project/config/conf.d:/etc/nginx/conf.d
      - ./volumes/home-page/home/html:/usr/share/nginx/html
  watchdog-svc:
    container_name: watchdog-c
    image: alpine:latest
    restart: unless-stopped
    command: /bin/sh
    stdin_open: true
    tty: true